#!/bin/bash

export ALLOWED_HOSTS=
export DATABASE_NAME=
export DATABASE_USER=
export DATABASE_PASSWORD=
export DATABASE_HOST=
export DATABASE_PORT=
export DATABASE_MONGODB_URI=
export MINIO_ACCESS_KEY=
export MINIO_SECRET_KEY=
export MINIO_BUCKET_NAME=
export MINIO_ENDPOINT=
export MAILJET_ACCESS_KEY=
export MAILJET_SECRET_KEY=
export MAILJET_DEFAULT_EMAIL=

python manage.py runserver 127.0.0.1:34515