# Generated by Django 3.2.16 on 2022-12-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ngaran',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=50)),
                ('work', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
