# Generated by Django 3.2.16 on 2022-12-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngaran', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngaran',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
