# Generated by Django 3.2.16 on 2022-12-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngaran', '0002_alter_ngaran_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngaran',
            name='nama',
        ),
        migrations.AddField(
            model_name='ngaran',
            name='name',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='ngaran',
            name='work',
            field=models.CharField(default='', max_length=100),
        ),
    ]
