# Generated by Django 3.2.16 on 2022-12-03 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngaran', '0003_auto_20221203_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ngaran',
            old_name='city',
            new_name='kota',
        ),
        migrations.RenameField(
            model_name='ngaran',
            old_name='name',
            new_name='nama',
        ),
        migrations.RenameField(
            model_name='ngaran',
            old_name='work',
            new_name='pekerjaan',
        ),
    ]
