# Generated by Django 4.1.13 on 2024-02-25 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_note.utils


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# simple_note.migrations.0015_auto_20240225_2221
# simple_note.migrations.0019_auto_20240225_2234

def fillTag(apps, schema_editor):
    for tag in Tag.objects.all():
        tag.created_at = timezone.now()
        tag.save()

def fillContact(apps, schema_editor):
    for contact in Contact.objects.all():
        contact.created_at = timezone.now()
        contact.save()

class Migration(migrations.Migration):

    replaces = [('simple_note', '0001_initial'), ('simple_note', '0002_note_created_at_note_owner'), ('simple_note', '0003_attachment_contact_tag_remove_note_name_and_more'), ('simple_note', '0004_remove_note_author_note_owner_alter_note_title'), ('simple_note', '0005_alter_note_owner'), ('simple_note', '0006_alter_attachment_file'), ('simple_note', '0007_remove_note_latitude_remove_note_longitude'), ('simple_note', '0008_alter_note_owner'), ('simple_note', '0009_remove_note_attachments_delete_attachment'), ('simple_note', '0010_contact_owner'), ('simple_note', '0011_alter_contact_owner'), ('simple_note', '0012_alter_contact_owner'), ('simple_note', '0013_alter_note_priority'), ('simple_note', '0014_tag_created_at'), ('simple_note', '0015_auto_20240225_2221'), ('simple_note', '0016_alter_tag_created_at'), ('simple_note', '0017_rename_name_tag_tag'), ('simple_note', '0018_contact_created_at'), ('simple_note', '0019_auto_20240225_2234'), ('simple_note', '0020_alter_contact_created_at')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('priority', models.IntegerField(default=0, validators=[simple_note.utils.priority_validator])),
                ('title', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('shared', 'Shared')], default='private', max_length=20)),
                ('related_contacts', models.ManyToManyField(to='simple_note.contact')),
                ('tags', models.ManyToManyField(to='simple_note.tag')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(
            fillTag,
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='tag',
        ),
        migrations.AddField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.RunPython(
            fillContact,
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
