# Generated by Django 4.1.13 on 2024-02-14 22:55

from django.db import migrations, models
import simple_note.utils


class Migration(migrations.Migration):

    dependencies = [
        ('simple_note', '0005_alter_note_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(null=True, upload_to=simple_note.utils.random_name),
        ),
    ]
