# Generated by Django 4.1.13 on 2024-02-14 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_note', '0006_alter_attachment_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='note',
            name='longitude',
        ),
    ]
