# Generated by Django 4.1.13 on 2024-02-15 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_note', '0008_alter_note_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='attachments',
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
