# Generated by Django 4.1.13 on 2024-02-25 07:28

from django.db import migrations, models
import simple_note.utils


class Migration(migrations.Migration):

    dependencies = [
        ('simple_note', '0012_alter_contact_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='priority',
            field=models.IntegerField(default=0, validators=[simple_note.utils.priority_validator]),
        ),
    ]
