# Generated by Django 4.1.13 on 2024-02-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_note', '0015_auto_20240225_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
