# Generated by Django 4.1.13 on 2024-02-25 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_note', '0016_alter_tag_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='tag',
        ),
    ]
