# Generated by Django 4.1.13 on 2024-02-25 15:34

from django.db import migrations
from django.utils import timezone
from simple_note.models import Contact

def fillContact(apps, schema_editor):
    for contact in Contact.objects.all():
        contact.created_at = timezone.now()
        contact.save()

class Migration(migrations.Migration):

    dependencies = [
        ('simple_note', '0018_contact_created_at'),
    ]

    operations = [
        migrations.RunPython(fillContact)
    ]
