# Generated by Django 4.1.13 on 2024-02-18 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User'},
        ),
    ]
