# Generated by Django 3.2.21 on 2024-02-12 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_user', '0003_customuser_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_superuser',
        ),
    ]
