# Generated by Django 3.2.21 on 2024-02-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_user', '0004_remove_customuser_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='wa',
            field=models.CharField(blank=True, max_length=15, verbose_name='WhatsApp'),
        ),
    ]
