# Generated by Django 3.2.21 on 2024-02-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_user', '0005_auto_20240212_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='wa',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
