# Generated by Django 4.2.10 on 2024-02-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_user', '0008_customuser_groups_customuser_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='wa',
            field=models.IntegerField(blank=True, max_length=15),
        ),
    ]
