# Generated by Django 4.2.10 on 2024-02-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_user', '0009_alter_customuser_wa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='wa',
            field=models.IntegerField(blank=True),
        ),
    ]
