# Generated by Django 4.2.10 on 2024-02-12 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_user', '0008_customuser_groups_customuser_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='wa',
        ),
    ]
