# Generated by Django 4.2.10 on 2024-02-12 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_user', '0012_remove_customuser_wa'),
        ('simple_user', '0013_merge_20240212_1438'),
    ]

    operations = [
    ]
