# Generated by Django 4.2.10 on 2024-02-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_user', '0014_merge_20240212_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='wa',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
