# Generated by Django 4.2.10 on 2024-02-12 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_user', '0015_customuser_wa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='wa',
        ),
    ]
