# Generated by Django 4.1.13 on 2024-02-12 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_user', '0017_customuser_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
