# Generated by Django 4.1.13 on 2024-02-12 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_user', '0018_customuser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
    ]
