# Generated by Django 4.1.13 on 2024-02-12 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_user', '0023_alter_customuser_whatsapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='whatsapp',
        ),
    ]
