# Generated by Django 4.1.13 on 2024-02-12 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_user', '0024_remove_customuser_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='whatsapp',
            field=models.IntegerField(blank=True, default=0, max_length=15),
        ),
    ]
