# Generated by Django 4.1.13 on 2024-02-13 07:46

from django.db import migrations, models
import simple_user.utils


class Migration(migrations.Migration):

    dependencies = [
        ('simple_user', '0028_alter_customuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, unique=True, upload_to=simple_user.utils.random_name),
        ),
    ]
