# Generated by Django 4.1.13 on 2024-02-13 08:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('simple_user', '0029_alter_customuser_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activation_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='activation_token_created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
