# Generated by Django 4.1.13 on 2024-02-13 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_user', '0030_customuser_activation_token_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='photo',
            new_name='image',
        ),
    ]
