# Generated by Django 4.1.13 on 2024-02-13 08:37

from django.db import migrations, models
import simple_user.utils


class Migration(migrations.Migration):

    dependencies = [
        ('simple_user', '0034_alter_customuser_activation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, upload_to=simple_user.utils.random_name),
        ),
    ]
