# Generated by Django 4.1.13 on 2024-02-18 06:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_catalog.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(choices=[('Cat', 'Cat'), ('Dog', 'Dog'), ('Bird', 'Bird'), ('Fish', 'Fish'), ('Other', 'Other')], max_length=50)),
                ('breed', models.CharField(max_length=75)),
                ('age', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('breed_group', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, choices=[('black', 'Black'), ('white', 'White'), ('brown', 'Brown'), ('gray', 'Gray'), ('orange', 'Orange'), ('yellow', 'Yellow'), ('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('other', 'Other')], max_length=50, null=True)),
                ('size', models.CharField(blank=True, choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=10, null=True)),
                ('health_status', models.CharField(blank=True, choices=[('healthy', 'Healthy'), ('sick', 'Sick'), ('injured', 'Injured'), ('other', 'Other')], max_length=50, null=True)),
                ('adoption_status', models.CharField(blank=True, choices=[('available', 'Available'), ('pending', 'Pending'), ('adopted', 'Adopted'), ('other', 'Other')], max_length=50, null=True)),
                ('intake_type', models.CharField(blank=True, choices=[('stray', 'Stray'), ('owner surrender', 'Owner Surrender'), ('rescue', 'Rescue'), ('other', 'Other')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnimalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=simple_catalog.utils.random_name)),
                ('animal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='simple_catalog.animal')),
            ],
        ),
    ]
