# Generated by Django 4.1.13 on 2024-02-25 15:47

from django.conf import settings
from django.db import migrations, models
from simple_catalog.models import Image
import django.db.models.deletion
import django.utils.timezone
import simple_catalog.utils
import uuid 

# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# simple_catalog.migrations.0006_auto_20240218_0838
# simple_catalog.migrations.0008_auto_20240218_0844
# simple_catalog.migrations.0025_auto_20240225_1544

def populate_created_at(apps, schema_editor):
    Image = apps.get_model('simple_catalog', 'Image')
    Image.objects.filter(created_at__isnull=True).update(created_at=timezone.now())

def givename(apps, schema_editor):
    images = Image.objects.all()
    for image in images:
        random = uuid.uuid4().hex
        image.name = random
        image.save()

class Migration(migrations.Migration):

    replaces = [('simple_catalog', '0001_initial'), ('simple_catalog', '0002_initial'), ('simple_catalog', '0003_rename_animalimage_image'), ('simple_catalog', '0004_image_owner'), ('simple_catalog', '0005_alter_image_owner'), ('simple_catalog', '0006_auto_20240218_0838'), ('simple_catalog', '0007_image_created_at'), ('simple_catalog', '0008_auto_20240218_0844'), ('simple_catalog', '0009_imagelist_animal_image_list'), ('simple_catalog', '0010_alter_animal_image_list'), ('simple_catalog', '0011_delete_imagelist'), ('simple_catalog', '0012_list_alter_animal_image_list'), ('simple_catalog', '0013_remove_animal_image_list'), ('simple_catalog', '0014_animal_image_list'), ('simple_catalog', '0015_remove_animal_image_list'), ('simple_catalog', '0016_delete_list'), ('simple_catalog', '0017_alter_image_owner'), ('simple_catalog', '0018_alter_image_owner'), ('simple_catalog', '0019_alter_image_owner'), ('simple_catalog', '0020_alter_image_animal'), ('simple_catalog', '0021_alter_image_image'), ('simple_catalog', '0022_alter_animal_adoption_status_alter_animal_color_and_more'), ('simple_catalog', '0023_remove_animal_breed_group'), ('simple_catalog', '0024_image_name'), ('simple_catalog', '0025_auto_20240225_1544'), ('simple_catalog', '0026_alter_image_name')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(choices=[('Cat', 'Cat'), ('Dog', 'Dog'), ('Bird', 'Bird'), ('Fish', 'Fish'), ('Other', 'Other')], max_length=50)),
                ('breed', models.CharField(max_length=75)),
                ('age', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('breed_group', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, choices=[('black', 'Black'), ('white', 'White'), ('brown', 'Brown'), ('gray', 'Gray'), ('orange', 'Orange'), ('yellow', 'Yellow'), ('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('other', 'Other')], max_length=50, null=True)),
                ('size', models.CharField(blank=True, choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=10, null=True)),
                ('health_status', models.CharField(blank=True, choices=[('healthy', 'Healthy'), ('sick', 'Sick'), ('injured', 'Injured'), ('other', 'Other')], max_length=50, null=True)),
                ('adoption_status', models.CharField(blank=True, choices=[('available', 'Available'), ('pending', 'Pending'), ('adopted', 'Adopted'), ('other', 'Other')], max_length=50, null=True)),
                ('intake_type', models.CharField(blank=True, choices=[('stray', 'Stray'), ('owner surrender', 'Owner Surrender'), ('rescue', 'Rescue'), ('other', 'Other')], max_length=50, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=simple_catalog.utils.random_name)),
                ('animal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='simple_catalog.animal')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RunPython(
            populate_created_at,
        ),
        migrations.RunPython(
            populate_created_at,
        ),
        migrations.AlterField(
            model_name='image',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='image',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='image',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='image',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='simple_catalog.animal'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=simple_catalog.utils.random_name),
        ),
        migrations.AlterField(
            model_name='animal',
            name='adoption_status',
            field=models.CharField(blank=True, choices=[('available', 'Available'), ('pending', 'Pending'), ('adopted', 'Adopted'), ('other', 'Other')], default='available', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='color',
            field=models.CharField(blank=True, choices=[('black', 'Black'), ('white', 'White'), ('brown', 'Brown'), ('gray', 'Gray'), ('orange', 'Orange'), ('yellow', 'Yellow'), ('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('other', 'Other')], default='other', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='health_status',
            field=models.CharField(blank=True, choices=[('healthy', 'Healthy'), ('sick', 'Sick'), ('injured', 'Injured'), ('other', 'Other')], default='healthy', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='intake_type',
            field=models.CharField(blank=True, choices=[('stray', 'Stray'), ('owner surrender', 'Owner Surrender'), ('rescue', 'Rescue'), ('other', 'Other')], default='other', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='size',
            field=models.CharField(blank=True, choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='small', max_length=10, null=True),
        ),
        migrations.RemoveField(
            model_name='animal',
            name='breed_group',
        ),
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.RunPython(
            givename,
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
