# Generated by Django 4.2.10 on 2024-02-12 11:15

from django.db import migrations
from django.utils import timezone

def populate_created_at(apps, schema_editor):
    Animal = apps.get_model('simple_catalog', 'Animal')
    for obj in Animal.objects.all():
        obj.created_at = timezone.now()
        obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('simple_catalog', '0003_animal_created_at'),
    ]

    operations = [
        migrations.RunPython(populate_created_at),
    ]
