# Generated by Django 4.1.13 on 2024-02-18 08:38

from django.db import migrations, models
from django.utils import timezone

def populate_created_at(apps, schema_editor):
    Image = apps.get_model('simple_catalog', 'Image')
    Image.objects.filter(created_at__isnull=True).update(created_at=timezone.now())

class Migration(migrations.Migration):

    dependencies = [
        ('simple_catalog', '0005_alter_image_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.RunPython(populate_created_at),
    ]
