# Generated by Django 4.1.13 on 2024-02-12 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_catalog', '0005_animalcount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnimalCount',
        ),
    ]
