# Generated by Django 4.1.13 on 2024-02-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_catalog', '0006_auto_20240218_0838'),
    ]

    operations = [
    ]
