# Generated by Django 4.1.13 on 2024-02-13 06:16

from django.contrib.auth import get_user_model
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def assign_animals_to_owner(apps, schema_editor):
    Animal = apps.get_model('simple_catalog', 'Animal')
    User = get_user_model()
    owner = User.objects.get(email='angga.sr57@gmail.com')
    animals_without_owner = Animal.objects.filter(owner__isnull=True)
    for animal in animals_without_owner:
        animal.owner = owner
        animal.save()

class Migration(migrations.Migration):

    dependencies = [
        ('simple_catalog', '0006_delete_animalcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(assign_animals_to_owner),
    ]
