# Generated by Django 4.1.13 on 2024-02-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_catalog', '0008_auto_20240218_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='image_list',
            field=models.ManyToManyField(to='simple_catalog.imagelist'),
        ),
    ]
