# Generated by Django 4.1.13 on 2024-02-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_catalog', '0009_imagelist_animal_image_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='image_list',
            field=models.ManyToManyField(blank=True, to='simple_catalog.animal'),
        ),
    ]
