# Generated by Django 4.1.13 on 2024-02-18 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_catalog', '0010_alter_animal_image_list'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageList',
        ),
    ]
