# Generated by Django 4.1.13 on 2024-02-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_catalog', '0011_delete_imagelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(max_length=10)),
            ],
        ),
    ]
