# Generated by Django 4.1.13 on 2024-02-18 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_catalog', '0015_remove_animal_image_list'),
    ]

    operations = [
        migrations.DeleteModel(
            name='List',
        ),
    ]
