# Generated by Django 4.1.13 on 2024-02-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_catalog', '0017_remove_animal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='test',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
