# Generated by Django 4.1.13 on 2024-02-25 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simple_catalog', '0019_alter_image_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='simple_catalog.animal'),
        ),
    ]
