# Generated by Django 4.1.13 on 2024-02-25 07:30

from django.db import migrations, models
import simple_catalog.utils


class Migration(migrations.Migration):

    dependencies = [
        ('simple_catalog', '0020_alter_image_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=simple_catalog.utils.random_name),
        ),
    ]
