# Generated by Django 4.1.13 on 2024-02-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_catalog', '0021_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='adoption_status',
            field=models.CharField(blank=True, choices=[('available', 'Available'), ('pending', 'Pending'), ('adopted', 'Adopted'), ('other', 'Other')], default='available', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='color',
            field=models.CharField(blank=True, choices=[('black', 'Black'), ('white', 'White'), ('brown', 'Brown'), ('gray', 'Gray'), ('orange', 'Orange'), ('yellow', 'Yellow'), ('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('other', 'Other')], default='other', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='health_status',
            field=models.CharField(blank=True, choices=[('healthy', 'Healthy'), ('sick', 'Sick'), ('injured', 'Injured'), ('other', 'Other')], default='healthy', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='intake_type',
            field=models.CharField(blank=True, choices=[('stray', 'Stray'), ('owner surrender', 'Owner Surrender'), ('rescue', 'Rescue'), ('other', 'Other')], default='other', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='size',
            field=models.CharField(blank=True, choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='small', max_length=10, null=True),
        ),
    ]
