# Generated by Django 4.1.13 on 2024-02-14 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_catalog', '0022_alter_animal_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='adoption_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='breed_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='health_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='intake_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='size',
            field=models.CharField(blank=True, choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
