# Generated by Django 4.1.13 on 2024-02-14 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_catalog', '0023_animal_adoption_status_animal_breed_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='color',
            field=models.CharField(blank=True, choices=[('black', 'Black'), ('white', 'White'), ('brown', 'Brown'), ('gray', 'Gray'), ('orange', 'Orange'), ('yellow', 'Yellow'), ('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
