# Generated by Django 4.1.13 on 2024-02-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_catalog', '0023_remove_animal_breed_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='', max_length=32),
        ),
    ]
