# Generated by Django 4.1.13 on 2024-02-25 08:44

from django.db import migrations
from simple_catalog.models import Image
import uuid 

def givename(apps, schema_editor):
    images = Image.objects.all()
    for image in images:
        random = uuid.uuid4().hex
        image.name = random
        image.save()

class Migration(migrations.Migration):

    dependencies = [
        ('simple_catalog', '0024_image_name'),
    ]

    operations = [
        migrations.RunPython(givename)
    ]
