# Generated by Django 4.1.13 on 2024-02-14 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_catalog', '0024_alter_animal_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='adoption_status',
            field=models.CharField(blank=True, choices=[('available', 'Available'), ('pending', 'Pending'), ('adopted', 'Adopted'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='health_status',
            field=models.CharField(blank=True, choices=[('healthy', 'Healthy'), ('sick', 'Sick'), ('injured', 'Injured'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='intake_type',
            field=models.CharField(blank=True, choices=[('stray', 'Stray'), ('owner surrender', 'Owner Surrender'), ('rescue', 'Rescue'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
