# Generated by Django 4.1.13 on 2024-02-14 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_catalog', '0025_alter_animal_adoption_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='species',
            field=models.CharField(choices=[('Cat', 'Cat'), ('Dog', 'Dog'), ('Bird', 'Bird'), ('Fish', 'Fish'), ('Other', 'Other')], max_length=50),
        ),
    ]
