# Generated by Django 4.1.13 on 2024-02-15 01:26

from django.db import migrations, models
import simple_catalog.utils


class Migration(migrations.Migration):

    dependencies = [
        ('simple_catalog', '0026_alter_animal_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=simple_catalog.utils.random_name),
        ),
    ]
