# Generated by Django 4.1.13 on 2024-02-25 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('simple_todo', '0001_initial'), ('simple_todo', '0002_remove_todo_completed_todo_owner_todo_status_and_more'), ('simple_todo', '0003_tag_todo_tags'), ('simple_todo', '0004_alter_todo_description'), ('simple_todo', '0005_rename_name_tag_tag'), ('simple_todo', '0006_tag_created_at')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL)),
                ('status', models.CharField(choices=[('PL', 'Planned'), ('OG', 'Ongoing'), ('DN', 'Done'), ('HD', 'On Hold'), ('CA', 'Canceled')], default='PL', max_length=2)),
                ('tags', models.ManyToManyField(to='simple_todo.tag')),
            ],
        ),
    ]
