# Generated by Django 4.1.13 on 2024-02-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_todo', '0002_remove_todo_completed_todo_owner_todo_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='todo',
            name='tags',
            field=models.ManyToManyField(to='simple_todo.tag'),
        ),
    ]
