# Generated by Django 4.1.13 on 2024-02-25 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_todo', '0003_tag_todo_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
