# Generated by Django 4.1.13 on 2024-02-25 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_todo', '0004_alter_todo_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='tag',
        ),
    ]
