name: Check Release and Execute Steps

on:
  push:
    branches:
      - master
  release:
    types: [published]

jobs:
  check-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set release tag
        id: set_release_tag
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "RELEASE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
            echo "RELEASE_EXISTS=true" >> $GITHUB_ENV
          else
            echo "RELEASE_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Display release status
        run: |
          echo "Release exists: ${{ env.RELEASE_EXISTS }}"

      - name: Execute if release exists
        if: ${{ env.RELEASE_EXISTS == 'true' }}
        run: echo "Release tag is ${{ env.RELEASE_TAG }}. Executing steps..."
