name: Check Release and Execute Steps

on:
  push:
    branches:
      - master

jobs:
  check-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check if release exists
        id: check_release
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "::set-output name=exists::true"
            echo "::set-output name=tag_name::${GITHUB_REF#refs/tags/}"
          else
            echo "::set-output name=exists::false"
          fi

      - name: Display release status
        run: echo "Release exists: ${{ steps.check_release.outputs.exists }}"

      - name: Execute if release exists
        if: ${{ steps.check_release.outputs.exists == 'true' }}
        run: echo "Release tag is ${{ steps.check_release.outputs.tag_name }}. Executing steps..."
